version: '3.8'

services:
  front:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: api:latest      # <-- Add this line
    container_name: node-api
    ports:
      - "5000:5000"

