name: Deploy React Frontend to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Build React frontend from 'public' folder using Yarn
      - name: Build React frontend
        working-directory: ./public
        run: |
          # Remove any leftover npm lockfile (safety)
          if [ -f package-lock.json ]; then
            rm package-lock.json
          fi

          # Rename env file if needed
          if [ -f .env.example ]; then
            mv .env.example .env
          fi

          # Install dependencies using Yarn
          yarn install --frozen-lockfile

          # Build the React app
          yarn build

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5️⃣ Create S3 bucket if it doesn't exist
      - name: Create S3 bucket
        run: |
          BUCKET_NAME="my-react-frontend-${{ github.run_id }}"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket \
              --bucket $BUCKET_NAME \
              --region ${{ secrets.AWS_REGION }} \
              --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
          fi

          aws s3api put-public-access-block \
            --bucket $BUCKET_NAME \
            --public-access-block-configuration '{
              "BlockPublicAcls": true,
              "IgnorePublicAcls": true,
              "BlockPublicPolicy": true,
              "RestrictPublicBuckets": true
            }'

      # 6️⃣ Attach S3 bucket policy for CloudFront
      - name: Attach bucket policy
        run: |
          BUCKET_NAME=$BUCKET_NAME
          CLOUDFRONT_ID=${{ secrets.CLOUDFRONT_ID }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          CLOUDFRONT_ARN="arn:aws:cloudfront::${ACCOUNT_ID}:distribution/${CLOUDFRONT_ID}"

          POLICY=$(cat <<EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AllowCloudFrontServicePrincipalRead",
                "Effect": "Allow",
                "Principal": {
                  "Service": "cloudfront.amazonaws.com"
                },
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::$BUCKET_NAME/*",
                "Condition": {
                  "StringEquals": {
                    "AWS:SourceArn": "$CLOUDFRONT_ARN"
                  }
                }
              }
            ]
          }
          EOF
          )

          echo "$POLICY" > bucket-policy.json
          aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://bucket-policy.json

      # 7️⃣ Upload React build to S3
      - name: Upload build to S3
        run: |
          aws s3 sync ./public/build/ s3://$BUCKET_NAME --delete

      # 8️⃣ Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
