name: Deploy React App to S3 + CloudFront (Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Install Docker + Docker Compose (already available in ubuntu-latest)
      - name: Verify Docker and Compose
        run: |
          docker --version
          docker compose version

      # ✅ Build React app with Docker Compose
      - name: Build React App using Docker Compose
        working-directory: simple-react-full-stack
        run: |
          docker compose build

      # ✅ Extract build artifacts from Docker image
      - name: Copy build files
        working-directory: simple-react-full-stack
        run: |
          CONTAINER_ID=$(docker create react-app)
          docker cp $CONTAINER_ID:/app/build ./build
          docker rm $CONTAINER_ID
          ls -l build

      # ✅ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ✅ Create S3 bucket (static or dynamic)
      - name: Create S3 bucket
        run: |
          BUCKET_NAME="my-react-app-${{ github.run_id }}"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket \
              --bucket $BUCKET_NAME \
              --region ap-south-1 \
              --create-bucket-configuration LocationConstraint=ap-south-1
          fi

      # ✅ Upload build to S3
      - name: Upload build to S3
        run: |
          aws s3 sync simple-react-full-stack/build/ s3://$BUCKET_NAME --delete

      # ✅ Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"
