name: Deploy React Frontend to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Verify Docker & Docker Compose
      - name: Verify Docker and Compose
        run: |
          docker --version
          docker compose version

      # 3️⃣ Build React frontend using Docker Compose
      - name: Build frontend
        working-directory: ./  # root of project
        run: docker compose build --no-cache front

      # 4️⃣ Run frontend container detached
      - name: Run frontend container
        working-directory: ./
        run: docker compose up -d front

      # 5️⃣ Extract React build
      - name: Extract React build
        working-directory: ./
        run: |
          FRONT_CONTAINER=$(docker ps -qf "name=react-frontend")
          docker cp $FRONT_CONTAINER:/usr/share/nginx/html ./build
          ls -l build

      # 6️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7️⃣ Create S3 bucket if it doesn't exist
      - name: Create S3 bucket
        run: |
          BUCKET_NAME="my-react-frontend-${{ github.run_id }}"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket \
              --bucket $BUCKET_NAME \
              --region ${{ secrets.AWS_REGION }} \
              --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
          fi

          aws s3api put-public-access-block \
            --bucket $BUCKET_NAME \
            --public-access-block-configuration '{
              "BlockPublicAcls": true,
              "IgnorePublicAcls": true,
              "BlockPublicPolicy": true,
              "RestrictPublicBuckets": true
            }'

      # 8️⃣ Attach S3 bucket policy for CloudFront
      - name: Attach bucket policy
        run: |
          BUCKET_NAME=$BUCKET_NAME
          CLOUDFRONT_ID=${{ secrets.CLOUDFRONT_ID }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          CLOUDFRONT_ARN="arn:aws:cloudfront::${ACCOUNT_ID}:distribution/${CLOUDFRONT_ID}"

          POLICY=$(cat <<EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AllowCloudFrontServicePrincipalRead",
                "Effect": "Allow",
                "Principal": {
                  "Service": "cloudfront.amazonaws.com"
                },
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::$BUCKET_NAME/*",
                "Condition": {
                  "StringEquals": {
                    "AWS:SourceArn": "$CLOUDFRONT_ARN"
                  }
                }
              }
            ]
          }
          EOF
          )

          echo "$POLICY" > bucket-policy.json
          aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://bucket-policy.json

      # 9️⃣ Upload React build to S3
      - name: Upload build to S3
        run: |
          aws s3 sync ./build/ s3://$BUCKET_NAME --delete

      # 🔟 Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
